### ISSUE TITLE
What to return for a POST method. 

### ISSUE THREAD

**Issue by hate-bug** [hate-bug/Covid-19-Tracking-Service#16]
@esfandia 
I did some research about what should REST API return for a POST method.
Here's an article that has a good point. https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#useful-post-responses. 
My question is: In our case, what URL should we return for the location header? For example, if a user successfully created a patient with some events and POST them to our service. I can return a successful code 201 with Content-Location: /getpatient?id=*patient_id*. Is this correct?

**Comment by esfandia** [comment]
@hate-bug If you're not doing any calculation in your controller, I think it's best to use custom CrudRepository methods and let Spring take care of crafting the response for you. It will do the right thing, setting the HTTP code and returning either the URI or the serialized object that you want. Which is the controller in question?
