### ISSUE TITLE
Come up with a high-level object-oriented design including Java Class Diagram and ORM.

### ISSUE THREAD

**Issue by hate-bug** [hate-bug/Covid-19-Tracking-Service#2]

**Comment by hate-bug** [comment]
@esfandia A quick question about the project requirement. 
Should we categorize events and allow user to pick? For example, user can choose "shopping" and enter the store location he went, or choose "work" and enter the work location. 
I think it's easier for users to make queries based on those categorize events.

**Comment by esfandia** [comment]
Eventually, definitely! We will also have to think about Places and whether they should be categorized by country, city, etc. For now, let's just build a simple MVP as per the exam, and then we can add these additional features.
